---
name: pre-commit

on:
  pull_request:
  push:
    branches:
      - develop
      - stage
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - uses: pre-commit/action@v3.0.1
